[package]
name = "aseprite-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
log = "0.4.19"
ron = "0.8.0"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0.133"
thiserror = "2.0.6"

[[example]]
name = "ex1"
